# Use the official Node.js image as a base
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy all the app files to the container
COPY . .

# Expose the app's port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]