version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  react-app:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - go-server

  go-server:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
